copy texcalc.py "C:\Programme (x86)\Miktex2.9\miktex\bin"
mkdir "C:\Programme (x86)\Miktex2.9\tex\latex\texcalc"
copy  texcalc.sty  "C:\Programme (x86)\Miktex2.9\tex\latex\texcalc\"
copy  contrib\anfpralayout.sty  "C:\Programme (x86)\Miktex2.9\tex\latex\texcalc\"
copy  contrib\physictools.sty  "C:\Programme (x86)\Miktex2.9\tex\latex\texcalc\"
