copy texcalc.py "C:\Program Files (x86)\MiKTeX 2.9\miktex\bin"
mkdir "C:\Program Files (x86)\MiKTeX 2.9\tex\latex\texcalc"
copy  texcalc.sty  "C:\Program Files (x86)\MiKTeX 2.9\tex\latex\texcalc\"
copy  contrib\anfpralayout.sty  "C:\Program Files (x86)\MiKTeX 2.9\tex\latex\texcalc\"
copy  contrib\physictools.sty  "C:\Program Files (x86)\MiKTeX 2.9\tex\latex\texcalc\"
